spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/codelab_db?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: codelab
    password: codelab
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace